
services:
  spring-app:
    image: hanjihoon0315/docker-springboot:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/jlaner?allowPublicKeyRetrieval=true  # MySQL 연결 URL
      - SPRING_DATASOURCE_USERNAME=root  # MySQL 사용자명
      - SPRING_DATASOURCE_PASSWORD=raik1353  # MySQL 비밀번호
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT= org.hibernate.dialect.MySQL8Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO= none
    restart: always
    depends_on:
      - redis
      - mysql  # MySQL 서비스에 의존성 추가

  nginx:
    image: hanjihoon0315/docker-nginx:latest
    ports:
      - "80:80"
    restart: always
    depends_on:
      - spring-app

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: raik1353  # MySQL 루트 비밀번호 설정
      MYSQL_DATABASE: jlaner  # 기본적으로 생성할 데이터베이스 이름
      TZ: Asia/Seoul
    ports:
      - "3307:3306"  # 로컬 호스트에서 3307 포트를 MySQL의 3306 포트로 매핑
    volumes:
      - mysql-data:/var/lib/mysql  # MySQL 데이터 영속화를 위한 볼륨 설정
      - ./jlaner.sql:/docker-entrypoint-initdb.d/jlaner.sql

volumes:
  redis-data:
  mysql-data:
