spring:
  thymeleaf:
  prefix: classpath:/templates/
  suffix: .html
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1020609323835-mph2ouc0i1ff6ij1a456bggach8gjo2s.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          naver:
            client-id: w_DLUzWW73Aizmc8OiSH
            client-secret: uIsa4FU6Fe
            client-authentication-method: client_secret_post
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            scope:
              - email
              - profile
          kakao:
            client-id: b8f3486575b72565c36b0c665b266365
            client-secret: 5GPcb4Iissy3tdmWA5I3pJ8TwXAgTsKB
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: # https://developers.kakao.com/docs/latest/ko/kakaologin/common#user-info
              - profile_nickname
              - account_email
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id # Kakao 응답 값 id, connected_at, properties, kakao_account 중 id 지정
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # Naver 응답 값 resultCode, message, response 중 response 지정
  datasource:
    #mysql 설정 부분
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://host.docker.internal:3306/project?serverTimezone=Asia/Seoul
    url: jdbc:mysql://127.0.0.1:3306/jlaner?serverTimezone=Asia/Seoul
    #    url: jdbc:mysql://testdb.czs22imqyijt.ap-northeast-2.rds.amazonaws.com:3306/testdb?serverTimezone=Asia/Seoul
    username: root
    password: raik1353
  jpa:
    #mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    #mysql
    hibernate:
      ddl-auto: create
    #      ddl-auto: create
    properties:
      hibernate:
        spring.jpa.open-in-view: false
        # show_sql: true # 주석 처리하여 주석 처리된 상태로 둠
        format_sql: true
        default_batch_fetch_size: 30
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        format_sql: true
#    defer-datasource-initialization: true
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/testcase
#    username: sa
#  h2:
#    console:
#      enabled: true
  redis:
    host: localhost
    port: 6379

logging:
  level:
    root: INFO
    org.springframework: INFO
    spring.jpa.open-in-view: false
    org.hibernate.SQL: info #debug
    org.hibernate.type.descriptor.sql: info #trace


jwt:
  secret_key: 0852712ba4290435a5c95068466f7cfb579762fe49b6879bb364055ba9ba90cb
