
services:
  spring-app-blue:
    image: hanjihoon0315/docker-springboot
    container_name: spring-app-blue
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/jlaner?serverTimezone=Asia/Seoul
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=raik1353
    restart: always
    depends_on:
      - redis
      - mysql  # MySQL 서비스에 의존성 추가
    networks:
      - backend

  spring-app-green:
    image: hanjihoon0315/docker-springboot
    container_name: spring-app-green
    ports:
      - "8081:8080"  # Green은 8081 포트를 사용
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/jlaner?serverTimezone=Asia/Seoul
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=raik1353
    restart: always
    depends_on:
      - redis
      - mysql
    networks:
      - backend

  redis:
    container_name: redis
#    build:
#      context: .
#      dockerfile: Dockerfile.redis
    image: hanjihoon0315/docker-redis
    hostname: redis
    ports:
      - "6379:6379"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - backend

  mysql:
    container_name: mysql
    image: hanjihoon0315/docker-mysql
    environment:
      MYSQL_ROOT_PASSWORD: raik1353  # MySQL 루트 비밀번호 설정
      MYSQL_DATABASE: jlaner  # 기본적으로 생성할 데이터베이스 이름
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql  # MySQL 데이터 영속화를 위한 볼륨 설정
      - ./jlaner.sql:/docker-entrypoint-initdb.d/jlaner.sql
    networks:
      - backend

volumes:
  redis-data:
  mysql-data:

networks:
  backend: